global:
  
route:
  receiver: 'email-receiver'

  repeat_interval: 10m

  routes:
  - match:
      service: inf
    receiver: email-receiver
  - match:
      service: mysql
    receiver: email-receiver


inhibit_rules:
- source_match:
    severity: 'critical'
  target_match:
    severity: 'warning'
  equal: ['alertname']

receivers:
- name: 'email-receiver'
  email_configs:
  - to: '0lgxzj0@gmail.com'
    smarthost: 'smtp.sendgrid.net:25'
    from: 'alert@em5348.lgxzj.wiki'
    auth_username: 'apikey'
    auth_password: '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'
    send_resolved: true
    require_tls: true
    tls_config:
      insecure_skip_verify: true