global:
  
route:
  receiver: 'email-receiver'

  group_by: ['alertname', 'cluster']

  group_wait: 30s

  group_interval: 5m

  repeat_interval: 10m

  routes:
  - match:
      service: inf
    receiver: email-receiver
  - match:
      service: mysql
    receiver: email-receiver


inhibit_rules:
- source_match:
    severity: 'critical'
  target_match:
    severity: 'warning'
  equal: ['alertname']

receivers:
- name: 'email-receiver'
  email_configs:
  - to: 'lgxzj@outlook.com'
    smarthost: 'smtp.qq.com:465'
    from: 'alertmanager@lgxzj.wiki'
    auth_username: '984144338@qq.com'
    auth_password: 'ydwmkvkarsokbfhe'
    send_resolved: true
    require_tls: true
    tls_config:
      insecure_skip_verify: true